### ISSUE TITLE
Improvement: Removal of unnecessary controllers

### ISSUE THREAD

**Issue by ASASauqui** [Josue0H/betsnap#15]
If you are not using the PageController and the home.html.heex inside controllers/page_html, it would be a good option to remove them.

**Comment by Josue0H** [comment]
Solved in: 13e95013f38943a27100981d84997a84dddae9b4

**Comment by ASASauqui** [comment]
<img width="472" alt="Screenshot 2024-03-12 at 12 09 28 p m" src="https://github.com/Josue0H/betsnap/assets/98852683/74f68427-a7b9-4c00-a767-07fd0ba50fda">

I think this is still not complete, for example you never use the page controller, you can remove both the PageController and its tests:

<img width="491" alt="Screenshot 2024-03-12 at 12 11 08 p m" src="https://github.com/Josue0H/betsnap/assets/98852683/a4057a38-88fe-47a3-8887-7e44e5cf986e">

**Comment by Josue0H** [comment]
Solved in: 6fc2f5b9eac4f2044ad148ff3a03f292833f3c61
